Use non-OpenHPC Slurm
stackhpc/ansible-role-openhpc pull request #163
Opened 2023-09-22 10:08 UTC by sjpb

Provides an `install-generic.yml` task book which can use existing Slurm binaries/libraries rather than installing OpenHPC packages.

Also adds `openhpc_config_files` to allow arbitrary Slurm configuration files to be templated.

2023-10-06 11:31 UTC, m-bull requested changes
This seems okay to me, but it would be nice to see the tests passing before it's merged

2023-10-10 10:06 UTC, sjpb commented
Tested on https://github.com/stackhpc/ansible-slurm-appliance/pull/312 slurm works, ood works, monitoring works.

2023-10-12 09:29 UTC, m-bull approved these changes

2024-02-21 09:06 UTC, sd109 submitted a review, later dismissed
LGTM

2025-09-04 15:25 UTC, sjpb commented
See appliance PR testing this here: https://github.com/stackhpc/ansible-slurm-appliance/pull/769

2025-09-09 10:04 UTC, merged