Fix duplication of nodes in NodeName
stackhpc/ansible-role-openhpc pull request #172
Opened 2024-11-08 15:04 UTC by jovial

Prior to this change slurmctld would fail to start if adding nodes to multiple partitions e.g:

    openhpc_slurm_partitions:
        - name: allnodes groups: - name: alfa - name: beta partition_params: Priority: 50 default: YES
        - name: alfa partition_params: Priority: 100 - name: bravo partition_params: Priority: 100

This change tracks all nodes that already have a NodeName entry and will not add again.

2024-11-08 15:25 UTC, jovial commented
This does not require using filters outside of the role like the workaround we have previously used:

```
# As per the docs:
# - A partition entry may contain groups. If it doesn't the partition itself is the group.
# - Nodes can only be in one group (else slurmctld startup fails with "fatal: Duplicated NodeName"
#   due to the templating approach. Howver $group.partition_params.Nodes can be used to
#   override the automatic definition of Node=.
# - To avoid having to explicitly list the nodes, we can use the hostlist_expression
#   filter provided by the stackhpc.openhpc role. This works as this expression is
#   evaluated inside the role. NB: this filter returns a list.
# - Have to handle the GPU nodes not existing in staging.
_general_nodes:
  - "{{ groups[openhpc_cluster_name + '_general'] | hostlist_expression | join(',') }}"
  - "{{ groups.get(openhpc_cluster_name + '_a40_1024', []) | hostlist_expression | join(',') }}"
  - "{{ groups.get(openhpc_cluster_name + '_a40_512', []) | hostlist_expression | join(',') }}"

openhpc_slurm_partitions:
  - name: general # all nodes except grid - this templates the actual ${cluster_name}-general nodes ...
    partition_params:
      Nodes: "{{ _general_nodes | join(',') }}" # .. this adds the other nodes
    default: YES
  - name: gpu # all GPU nodes
    groups:
      - name: a40_1024
        gres:
          - conf: gpu:A40:2
            file: /dev/nvidia[0-1]
      - name: a40_512
        gres:
          - conf: gpu:A40:2
            file: /dev/nvidia[0-1]
    default: NO
```

2024-11-08 16:14 UTC, sjpb commented
Can someone add a molecule test for this specific case please?

2024-11-08 16:23 UTC, sjpb requested changes
Can we get a) a molecule test and b) docs changes to match up with code behaviour changes please.

2024-11-18 09:33 UTC, jianguo-ukaea reviewed
I have written a molecule test named test15 for this change. May I know how to include the test?

2024-11-19 13:36 UTC, jianguo-ukaea commented
@sjpb Thank you. The README had been updated in my repo as well(see my previous message); Let me know if there is anything missing.

2024-11-20 13:59 UTC, jovial commented
Closing in favor in #174

2024-11-20 13:59 UTC, closed without merging