Add support for enabling slurmdbd
stackhpc/ansible-role-openhpc pull request #46
Opened 2020-08-21 11:57 UTC by jovial

2020-11-10 12:34 UTC, jovial commented on molecule/test4/verify.yml
> +  - name: Allow sum time for the job to complete
```suggestion
  - name: Allow some time for the job to complete
```

2020-11-17 09:54 UTC, sjpb requested changes

2020-11-17 09:54 UTC, sjpb commented on README.md
> +`openhpc_slurmdbd_host`: Where to deploy slurmdbd if are using this role to deploy slurmdbd, otherwise where
Needs to specifiy that default is `openhpc_slurm_control_host`

2020-11-17 09:54 UTC, sjpb commented on README.md
> +* Configure a mariadb or mysql server as documented in the slurm accounting (documentation)[https://slurm.schedmd.com/accounting.html]
From this and the following point, it's not clear to me if they have to be the same node? If so I'd suggest replacing both with:
 
- Configure a mariadb or mysql server as described in the slurm accounting [documentation](https://slurm.schedmd.com/accounting.html) on one of the nodes in your inventory and set `openhpc_enable.database` to `true` for this node.

If not, just fix the doc link markup/works as above anyway!

2020-11-18 12:36 UTC, jovial commented
Thanks for the review. Think I've addressed everything now.

2020-11-18 13:10 UTC, sjpb requested changes
Needs one line deleting in README

2020-11-18 13:10 UTC, sjpb commented on README.md
> +* Set `openhpc_enable.database` to `true` for one of the nodes in your inventory
Duplicates above line.

2020-11-18 17:00 UTC, jovial commented on README.md
> +* Set `openhpc_enable.database` to `true` for one of the nodes in your inventory
```suggestion
```

2020-11-18 17:01 UTC, jovial commented on README.md
> +* Set `openhpc_enable.database` to `true` for one of the nodes in your inventory
Good spot, thanks.

2020-11-19 09:19 UTC, sjpb approved these changes

2020-11-19 09:19 UTC, merged